version: "3"
services:
# Coturn
  coturn:
    image: coturn/coturn:latest
    restart: always
    volumes:
      - /etc/turnserver.conf:/etc/turnserver.conf:ro
      - /etc/letsencrypt/live/thiscord.com.tr/fullchain.pem:/etc/letsencrypt/live/thiscord.com.tr/fullchain.pem:ro
      - /etc/letsencrypt/live/thiscord.com.tr/privkey.pem:/etc/letsencrypt/live/thiscord.com.tr/privkey.pem:ro
    ports:
## STUN/TURN
      - "3478:3478"
      - "3478:3478/udp"
      - "3479:3479"
      - "3479:3479/udp"
## STUN/TURN SSL
      - "5349:5349"
      - "5349:5349/udp"
      - "5350:5350"
      - "5350:5350/udp"
# Relay Ports
      - "49152-49300:49152-49300/udp"