[package]
name = "front-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
uuid = { version = "1.17.0", features = ["v4"] }
